"""se crea tabla usuario

Revision ID: 2a7724cb5d88
Revises: 
Create Date: 2025-05-16 11:35:42.014228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7724cb5d88'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=True),
    sa.Column('ubicacion', sa.String(length=30), nullable=True),
    sa.Column('descripcion', sa.String(length=30), nullable=True),
    sa.Column('numero_dias', sa.Integer(), nullable=True),
    sa.Column('numero_noches', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=True),
    sa.Column('apellido', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=30), nullable=True),
    sa.Column('celular', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=True),
    sa.Column('descripcion', sa.String(length=30), nullable=True),
    sa.Column('fecha_inicio', sa.Integer(), nullable=True),
    sa.Column('fecha_fin', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    op.drop_table('user')
    op.drop_table('planes')
    # ### end Alembic commands ###
